contest_directory = "~/procon/{service_domain}/{contest_id}/{problem_id}"
problem_directory = "~/procon/{service_domain}/{contest_id}/{problem_id}"

[templates]
"main.cpp" = "empty.cpp"
"test/in" = "empty.cpp"
